export { default as Layout } from "./layout/Layout"
export { default as Header } from "./header/Header"
export { default as Workship } from "./workship/Workship"
export { default as ParalaxPhoto } from "./paralaxPhoto/ParalaxPhoto"
export { default as Quote } from "./quote/Quote"
export { default as Blog } from "./blog/Blog"
